services:
  lhk_django_backend:
    build:
      context: ./backend
    container_name: lhk_django_backend
    ports:
      - "8000:8000"
    command: ["sh", "./start.sh"]
    env_file:
      - ./backend/.env
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env

  lhk_react_frontend:
    build:
      context: ./frontend
    container_name: lhk_react_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_HOST=0.0.0.0
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - lhk_django_backend

  reverse_proxy:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - lhk_django_backend
      - lhk_react_frontend

volumes:
  postgres_data:
