# Generated by Django 5.1.6 on 2025-03-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_options_alter_user_is_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('access_vendor_dashboard', 'Can access vendor dashboard'), ('add_product', 'Can add products to the site'), ('send_newsletter', 'Can send newsletters to suscribers')]},
        ),
    ]
