# Generated by Django 5.1.6 on 2025-03-21 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('access_vendor_dashboard', 'Can access vendor dashboard'), ('send_newsletter', 'Can send newsletters to suscribers')]},
        ),
    ]
