version: "3.8"

services:
  web:
    build:  # ✅ Fix extra colon
      context: .
    container_name: web
    ports:
      - "8000:8000"
    command: ["sh", "./start.sh"]
    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:  # ✅ Move it out from under "web"
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres_data:
