# Generated by Django 5.1.6 on 2025-10-23 13:43

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producttag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_producttag_name_ci'),
        ),
    ]
