# Generated by Django 5.1.6 on 2025-10-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_producttag_uniq_producttag_name_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttag',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
    ]
