name: Publish Backend to Docker Hub and Config Droplet

on:
  release:
    types: [published]

env:
  IMAGE_REPO: dio/lhk-backend
  IMAGE_TAG_LATEST: backend-latest
  IMAGE_TAG_SHA: backend-${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # --- BACKEND ---
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG_LATEST }}
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG_SHA }}

  sync-configs:
    runs-on: ubuntu-24.04
    needs: build-and-push
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Ensure target folders on droplet
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY}}
          script: |
            mkdir -p ~/lhk-stack/prod-ver/nginx

      - name: Copy production infra files to droplet
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "prod-ver/docker-compose.prod.yml, prod-ver/nginx/nginx-droplet-api.conf"
          target: "~/lhk-stack/"

  deploy:
    runs-on: ubuntu-24.04
    needs: sync-configs
    steps:
      - name: Apply NGINX & Deploy Backend (Update Droplet)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY}}
          script: |
            set -e

            #---NGINX---
            #copies versioned config into sys location
            sudo cp -f ~/lhk-stack/prod-ver/nginx/nginx-droplet-api.conf /etc/nginx/sites-available/nginx-droplet-api.conf
            sudo ln -sf /etc/nginx/sites-available/nginx-droplet-api.conf /etc/nginx/sites-enabled/nginx-droplet-api.conf
            sudo nginx -t
            sudo systemctl reload nginx

            #---Compose--
            cd ~/lhk-stack/prod-ver
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans

            docker image prune -f

      - name: Health Check
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY}}
          script: |
            curl -fsSL https://api.example.com/healthz >/dev/null
